### PR TITLE
Update examples to contain an attachment reply test

### PR DESCRIPTION
**Pull request by ParisLiakos**
Seems its not that easy as seen on #53
Added an example. Sorry for converting the line endings to Unix ones in the process

### CODE REVIEW

**Comment by oijkn** [comment]
@ParisLiakos Thank you very much mate for this example ! I tried it and it works pretty good :)

The only little issue is when i do a reply with attachments, the name of the file is not good. It changed by number like "0" or "1" etc... So there is a way to get the good name of files uploaded please ?

```
$url = "http://rt.easter-eggs.org/demos/4.2/";
$user = "admin";
$pass = "admin";

$rt = new RequestTracker($url, $user, $pass);

$attachments = [
    new \CURLFile('C:\wamp\www\smaRT-v0.6\tests\sample.doc', 'application/msword', 'filename=sample.doc'),
    new \CURLFile('C:\wamp\www\smaRT-v0.6\tests\pdf-sample.pdf', 'application/pdf', 'filename=pdf-sample.pdf'),
];

$content = array(
    'Text' => 'This is a test reply from PHP.',
);
$response = $rt->doTicketReply(233, $content, $attachments);
print_r($response);
```
I want to thanks you very much for helping me in this !! You make my day mate :) and thank you for your great contribution !!

Best regards.

**Comment by ParisLiakos** [comment]
no problem :)
dunno, maybe it is something that RT does on the demo site because there is an existing file on disk with the same name already uploaded? 
For me the filenames stay the same on RT 4.2.12

**Comment by ParisLiakos** [comment]
Or, maybe..wait. i think i know the problem ;) Updating the example

**Comment by oijkn** [comment]
@ParisLiakos Sorry to answer you a little late but i was busy...

I would like to tell you that before asking your help i tried many things and of course your last changes too but the result is the same...

To eliminate all sources of error from the demo site i tried on our real RT server and the result is the same, the name of files is not the same from the code. The final name of files ae like to the attached file (screenshoot).

I don't know what to do because i tried many things and nothing fix the issue for file name :\
!

[capture]
(https://cloud.githubusercontent.com/assets/18188407/14189821/b0abd65e-f78f-11e5-8fd4-49ccba463e93.PNG)

Thank you very much in advance for your help ParisLiakos !!

Best regards.

**Comment by ParisLiakos** [comment]
ah, right, array keys must be the filenames. fixing example..

**Comment by oijkn** [comment]
Hi ParisLiakos,

Good call mate !! All that works perfectly :) Thank you very much for this fix !!

Have a good day, regards.

**Pull request merged**
