### PR TITLE
PSR-4 Compliance

### PR DESCRIPTION
**Pull request by alandrees**
Modified to be PSR-4 Compliant

### CODE REVIEW

**Comment by dersam** [comment]
This is a major backwards compatibility break.  However, it's definitely something I've wanted to do for a while as a 2.0 release (see #43).

There are three items blocking the merge:

1. The unit tests need to be updated to use the autoloader appropriately.  It's probably a small modification to [tests/bootstrap.php](https://github.com/dersam/RTPHPLib/blob/master/tests/bootstrap.php).

2.  I don't think a separate namespace for the exceptions is necessary. Please move those into the Dersam/RequestTracker namespace.

3. While we're breaking backwards compatibility, we might as well change the class name. I think `Dersam\RequestTracker\RequestTracker` is kind of clunky. `Dersam\RequestTracker\Client` looks much cleaner.

If these items are resolved, I'll merge this PR as a new major version.

**Comment by alandrees** [comment]
closing for updated pr

**Comment by dersam** [comment]
Please keep all additional work related to this feature in this PR. No need to open a new one for updates, the tests will run on each new push.

You can view the test output for your last push at https://travis-ci.org/dersam/RTPHPLib/builds/179045010.

**Comment by dersam** [comment]
Closing for inactivity.

**Pull request closed without merging**
