### PR TITLE
search method does not account for queue user or groups

### PR DESCRIPTION
**Pull request by ParisLiakos**

### CODE REVIEW

**Comment by ParisLiakos** [comment]
This probably needs to go in 1.1.0, because it changes the method signature

**Comment by dersam** [comment]
Semver would require that this be in version 2.0, as it breaks backwards compatibility.

I'd prefer if we maintained BC for now. A signature of 
`$query='', $orderBy='', $format='s',$type='ticket'`
would be acceptable for a merge into a minor version.

I'm currently in the process of speccing out how I want to do version 2, which will include support for the new JSON api.  BC changes are currently fair game.

**Comment by ParisLiakos** [comment]
You are right! I did that and also added some convenience wrappers, so it is more developer friendly

**Comment by dersam** [comment]
:+1:

**Pull request merged**
